package it.saimao.shan_converter.converters;

public class ShanAyingConverter {
    public static String ayingToShan(String input) {
        String output = input;
        output = output.replaceAll("\\u0075", "ၵ")
                .replaceAll("\\u0063", "ၶ")
                .replaceAll("\\u0069", "င")
                .replaceAll("\\u0071", "ၸ")
                .replaceAll("\\u006f", "သ")
                .replaceAll("\\u0070", "ၺ")
                .replaceAll("\\u0077", "တ")
                .replaceAll("\\u0078", "ထ")
                .replaceAll("[\\u0065\\u008f\\u0090]", "ၼ")
                .replaceAll("\\u0079", "ပ")
                .replaceAll("\\u007a", "ၽ")
                .replaceAll("[\\u005a\\u0050]", "ၾ")
                .replaceAll("\\u0072", "မ")
                .replaceAll("\\u002c", "ယ")
                .replaceAll("[\\u0037\\u0026]", "ရ")
                .replaceAll("\\u0076", "လ")
                .replaceAll("\\u0030", "ဝ")
                .replaceAll("\\u005b", "ႁ")
                .replaceAll("\\u006e", "ဢ")
                .replaceAll("\\u0062", "ႇ")
                .replaceAll("\\u006a", "ႈ")
                .replaceAll("\\u003b", "း")
                .replaceAll("[\\u0068\\u0055]", "့")
                .replaceAll("\\u0047", "ႉ")
                .replaceAll("\\u0073", "ျ")
                .replaceAll("[\\u0059\\u003a\\u007c]", "ြ")
                .replaceAll("\\u0040", "ႊ")
                .replaceAll("\\u0074", "ႄ")
                .replaceAll("[\\u0061\\u0027]", "ေ")
                .replaceAll("\\u0041", "ဵ")
                .replaceAll("\\u0046", "ႅ")
                .replaceAll("\\u006d", "ၢ")
                .replaceAll("\\u004d", "ႃ")
                .replaceAll("\\u0067", "ႂ")
                .replaceAll("\\u0066", "်")
                .replaceAll("\\u0042", "ႆ")
                .replaceAll("[\\u006b\\u004b]", "ု")
                .replaceAll("[\\u006c\\u004c]", "ူ")
                .replaceAll("\\u0056", "ၿ")
                .replaceAll("\\u0058", "ꩡ")
                .replaceAll("\\u0057", "ၻ")
                .replaceAll("\\u0023", "ၷ")
                .replaceAll("\\u0064", "ိ")
                .replaceAll("\\u0044", "ီ")
                .replaceAll("\\u003f", "၊")
                .replaceAll("\\u002f", "။")
                .replaceAll("\\u002e", "ွ")
                .replaceAll("\\u003d", "ႁူ")
                .replaceAll("\\u002b", "ႁွ")
                .replaceAll("\\u0043", "ႉႉႉ")
                .replaceAll("\\u007b", "ႁႂ်")
                .replaceAll("\\u0052", "ျွ")
                .replaceAll("\\u0031", "၁")
                .replaceAll("\\u0032", "၂")
                .replaceAll("\\u0033", "၃")
                .replaceAll("\\u0034", "၄")
                .replaceAll("\\u0035", "၅")
                .replaceAll("\\u0036", "၆")
                .replaceAll("\\u005e", "၇")
                .replaceAll("\\u0038", "၈")
                .replaceAll("\\u0039", "၉")
                .replaceAll("([\\u1031\\u1084\\u103c])([\\u1000-\\u1081\\u1022])", "$2$1")
                .replaceAll("(\\u102f)(\\u102d)", "$2$1")
                .replaceAll("(\\u1030)(\\u102d)", "$2$1");

        return output;

    }
}
